=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/archivo/archivo.dtd
<!ELEMENT catalogo (producto+)>
<!ELEMENT producto (nombre, marca, descripcion, precio, comentarios)>
<!ATTLIST producto id CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #REQUIRED>
<!ELEMENT comentarios (comentario+)>
<!ELEMENT comentario (usuario, texto)>
<!ELEMENT usuario (#PCDATA)>
<!ELEMENT texto (#PCDATA)>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/archivo/archivo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE catalogo SYSTEM "archivo.dtd">
<catalogo>
    <producto id="1">
        <nombre>Portátil UltraX</nombre>
        <marca>SuperTech</marca>
        <descripcion><![CDATA[
            La serie UltraX de SuperTech es conocida por su rendimiento excepcional y diseño ultradelgado.
            ¡Experimenta la potencia en tus manos con este portátil de última generación!
        ]]></descripcion>
        <precio moneda="USD">1499.99</precio>
        <comentarios>
            <comentario>
                <usuario>Usuario1</usuario>
                <texto><![CDATA[
                    Este portátil es increíble, supera todas mis expectativas.
                    No puedo creer lo delgado que es y lo rápido que funciona.
                ]]></texto>
            </comentario>
            <comentario>
                <usuario>Usuario2</usuario>
                <texto><![CDATA[
                    Excelente relación calidad-precio. Ideal para tareas intensivas y gaming.
                ]]></texto>
            </comentario>
        </comentarios>
    </producto>

</catalogo>
