=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/xsd/ejercicios/libro2/libro2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca" type="Tbiblioteca" />

    <xs:complexType name="Tbiblioteca">
        <xs:sequence>
            <xs:element name="autor" type ="Tautor" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Tautor">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="anioNacimiento" type="xs:integer"/>
            <xs:element name="libro" type="Tlibro" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Tlibro">
        <xs:sequence>
            <xs:element name="titulo" type="xs:string"/>
            <xs:element name="fechaPublicacion" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/xsd/ejercicios/libro2/libro2.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="libro2.xsd">
    <autor>
        <nombre>J.K. Rowling</nombre>
        <anioNacimiento>1965</anioNacimiento>
        <libro>
            <titulo>Harry Potter and the Philosopher's Stone</titulo>
            <fechaPublicacion>1997</fechaPublicacion>
        </libro>
        <libro>
            <titulo>Harry Potter and the Chamber of Secrets</titulo>
            <fechaPublicacion>1998</fechaPublicacion>
        </libro>
    </autor>
    <autor>
        <nombre>George Orwell</nombre>
        <anioNacimiento>1903</anioNacimiento>
        <libro>
            <titulo>1984</titulo>
            <fechaPublicacion>1949</fechaPublicacion>
        </libro>
    </autor>
</biblioteca>
