=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/xsd/ejercicios/empresa/empleados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa" type="tEmpresa" />

    <xs:complexType name="tEmpresa">
        <xs:sequence>
            <xs:element name="empleado" type="tEmpleado" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tEmpleado">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="departamento" type="xs:string" />
            <xs:element name="proyectos" type="tProyectos"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="tProyectos">
        <xs:sequence>
            <xs:element name="proyecto" type="tProyecto" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tProyecto">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="estado" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="tipo" type="tTipo" />
    </xs:complexType>

    <xs:simpleType name="tTipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="IT"/>
            <xs:enumeration value="Marketing"/>
            <xs:enumeration value="Recruitment"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/xsd/ejercicios/empresa/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="empleados.xsd">
    <empleado id="E001">
        <nombre>John Doe</nombre>
        <departamento>Desarrollo</departamento>
        <proyectos>
            <proyecto tipo="IT">
                <nombre>Sistema de Gestión</nombre>
                <estado>En Progreso</estado>
            </proyecto>
            <proyecto tipo="Marketing">
                <nombre>Campaña Publicitaria</nombre>
                <estado>Completado</estado>
            </proyecto>
        </proyectos>
    </empleado>
    <empleado id="E002">
        <nombre>Jane Smith</nombre>
        <departamento>Recursos Humanos</departamento>
        <proyectos>
            <proyecto tipo="Recruitment">
                <nombre>Contratación de Personal</nombre>
                <estado>Planificado</estado>
            </proyecto>
        </proyectos>
    </empleado>
</empresa>
