=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/empresa/empresa.dtd
<!ELEMENT empresa (nombreEmpresa, fundacion, empleados)>

<!ELEMENT nombreEmpresa (#PCDATA)>
<!ELEMENT fundacion EMPTY>
<!ATTLIST fundacion
    anio CDATA #REQUIRED
    mes CDATA #REQUIRED
    dia CDATA #REQUIRED
>

<!ELEMENT empleados (empleado+)>

<!ELEMENT empleado (nombre, puesto, salario, proyectos?)>
<!ATTLIST empleado
    id CDATA #REQUIRED
>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT puesto (titulo, departamento)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT salario (#PCDATA)>
<!ATTLIST salario
    moneda (USD | EUR | GBP) #REQUIRED
>

<!ELEMENT proyectos (proyecto+)>

<!ELEMENT proyecto (descripcion, responsable, fechas)>
<!ATTLIST proyecto
    nombre CDATA #REQUIRED
>

<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT responsable (#PCDATA)>
<!ELEMENT fechas (inicio, fin)>
<!ELEMENT inicio EMPTY>
<!ATTLIST inicio
    anio CDATA #REQUIRED
    mes CDATA #REQUIRED
    dia CDATA #REQUIRED
>

<!ELEMENT fin EMPTY>
<!ATTLIST fin
    anio CDATA #REQUIRED
    mes CDATA #REQUIRED
    dia CDATA #REQUIRED
>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/empresa/empresa.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE empresa SYSTEM "empresa.dtd">
<empresa>
    <nombreEmpresa>Empresa XYZ</nombreEmpresa>
    <fundacion anio="2000" mes="10" dia="15"/>
    <empleados>
        <empleado id="1">
            <nombre>Juan Pérez</nombre>
            <puesto>
                <titulo>Desarrollador Senior</titulo>
                <departamento>Desarrollo</departamento>
            </puesto>
            <salario moneda="USD">75000.00</salario>
            <proyectos>
                <proyecto nombre="Sistema XYZ">
                    <descripcion><![CDATA[
                        Desarrollo de un sistema integral para gestionar procesos internos y mejorar la eficiencia.
                    ]]></descripcion>
                    <responsable>María Gómez</responsable>
                    <fechas>
                        <inicio anio="2022" mes="02" dia="01"/>
                        <fin anio="2023" mes="06" dia="30"/>
                    </fechas>
                </proyecto>
                <proyecto nombre="Sistema XYZ">
                    <descripcion><![CDATA[
                        Desarrollo de un sistema integral para gestionar procesos internos y mejorar la eficiencia.
                    ]]></descripcion>
                    <responsable>María Gómez</responsable>
                    <fechas>
                        <inicio anio="2022" mes="02" dia="01"/>
                        <fin anio="2023" mes="06" dia="30"/>
                    </fechas>
                </proyecto>
            </proyectos>
        </empleado>
    </empleados>
</empresa>
