=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/tarea2/base/DTD/club.dtd
<!-- Definición del elemento principal: club_voleibol -->
<!ELEMENT club_voleibol (tienda?, equipo+, partido*)>

<!-- Definición del elemento tienda con atributo ubicacion -->
<!ELEMENT tienda (articulo+)>
<!ATTLIST tienda ubicacion CDATA #REQUIRED>

<!-- Definición del elemento articulo con atributos marca, foto y cod -->
<!ELEMENT articulo (tipoarticulo, descripcion, precio, comentarios*)>
<!ATTLIST articulo marca CDATA #REQUIRED
                foto CDATA #REQUIRED
                cod ID #REQUIRED> <!-- Se utiliza ID para indicar que el valor de cod debe ser único -->

<!-- Definición de elementos internos del articulo: tipoarticulo, descripcion, precio y comentarios -->
<!ELEMENT tipoarticulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT comentarios (#PCDATA)>
<!ATTLIST comentarios fecha CDATA #REQUIRED>

<!-- Definición del elemento equipo con atributo categoria -->
<!ELEMENT equipo (jugadores, denominacion, entrenador)>
<!ATTLIST equipo categoria CDATA #REQUIRED>

<!-- Definición del elemento jugadores -->
<!ELEMENT jugadores (jugador+)>


<!-- Definición del elemento jugador con atributos camiseta y titular -->
<!ELEMENT jugador (nombre, posicion, nacionalidad)>
<!ATTLIST jugador camiseta CDATA #REQUIRED
                titular CDATA "no">

<!-- Definición de elementos internos del jugador: nombre, posicion y nacionalidad -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>

<!-- Definición de elementos internos del jugador: nombre, posicion y nacionalidad -->
<!ELEMENT denominacion (#PCDATA)>
<!ELEMENT entrenador (entrenador_nombre, entrenador_url)>
<!ELEMENT entrenador_nombre (#PCDATA)>
<!ELEMENT entrenador_url (#PCDATA)>

<!-- Definición del elemento partido con atributos lugar, fecha y elementos teams y arbitro -->
<!ELEMENT partido (lugar, fecha, teams, arbitro)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

<!-- Definición del elemento teams con elementos team y atributo opcional local -->
<!ELEMENT teams (team*, team?)>

<!-- Definición del elemento team con atributos local y puntuacion -->
<!ELEMENT team (#PCDATA)>
<!ATTLIST team local CDATA #IMPLIED 
               puntuacion CDATA #REQUIRED>

<!-- Definición del elemento arbitro con elementos arbitro_nombre y arbitro_nacionalidad y atributo categoria -->
<!ELEMENT arbitro (arbitro_nombre, arbitro_nacionalidad)>
<!ATTLIST arbitro categoria (internacional|nacional|regional) #REQUIRED>
<!ELEMENT arbitro_nombre (#PCDATA)>
<!ELEMENT arbitro_nacionalidad (#PCDATA)>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/tarea2/base/DTD/club.xml
<!DOCTYPE club_voleibol SYSTEM "./club.dtd">
<club_voleibol>
    <tienda ubicacion="Bilbao">
        <articulo marca="Nike" foto="img.jpg" cod="AB123456A">
            <tipoarticulo>Camiseta oficial</tipoarticulo>
            <descripcion>Camiseta oficial del club</descripcion>
            <precio>29.99</precio>
            <comentarios fecha="2023-07-01">Muy cómoda</comentarios>
            <comentarios fecha="2023-07-02">Muy cómoda</comentarios>
        </articulo>
    </tienda>
    <!--  Información del equipo  -->
    <equipo categoria="Segunda">
        <jugadores>
            <jugador camiseta="7" titular="si">
                <nombre>Luis García</nombre>
                <posicion>Atacante</posicion>
                <nacionalidad>Argentina</nacionalidad>
            </jugador>
            <jugador camiseta="3" titular="no">
                <nombre>Ana Silva</nombre>
                <posicion>Libero</posicion>
                <nacionalidad>Brasil</nacionalidad>
            </jugador>
        </jugadores>
        <denominacion>Club VolleyTeam</denominacion>
        <entrenador>
            <entrenador_nombre>Julio Velasco</entrenador_nombre>
            <entrenador_url>www.wikipedia.org/wiki/Julio_Velasco</entrenador_url>
        </entrenador>
    </equipo>
    <equipo categoria="Segunda">
        <jugadores>
            <jugador camiseta="7" titular="si">
                <nombre>Luis García</nombre>
                <posicion>Atacante</posicion>
                <nacionalidad>Argentina</nacionalidad>
            </jugador>
            <jugador camiseta="3" titular="no">
                <nombre>Ana Silva</nombre>
                <posicion>Libero</posicion>
                <nacionalidad>Brasil</nacionalidad>
            </jugador>
        </jugadores>
        <denominacion>Club VolleyTeam B</denominacion>
        <entrenador>
            <entrenador_nombre>Julio Velasco</entrenador_nombre>
            <entrenador_url>www.wikipedia.org/wiki/Julio_Velasco</entrenador_url>
        </entrenador>
    </equipo> 
    <!--  Información del partido  -->
    <partido>
        <lugar>Estadio Nacional</lugar>
        <fecha>2023-08-01</fecha>
        <teams>
            <team local="si" puntuacion="20">Equipo A</team>
            <team local="no" puntuacion="25">Equipo B</team>
        </teams>
        <arbitro categoria="internacional">
            <arbitro_nombre>Juan Pérez</arbitro_nombre>
            <arbitro_nacionalidad>Argentina</arbitro_nacionalidad>
        </arbitro>
    </partido>
    <partido>
        <lugar>Estadio Nacional</lugar>
        <fecha>2023-08-01</fecha>
        <teams>
            <team local="si" puntuacion="20">Equipo A</team>
            <team  puntuacion="25">Equipo B</team>
        </teams>
        <arbitro categoria="nacional">
            <arbitro_nombre>Juan Pérez</arbitro_nombre>
            <arbitro_nacionalidad>Argentina</arbitro_nacionalidad>
        </arbitro>
    </partido>
</club_voleibol>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/tarea2/base/club.xml
<!-- <!DOCTYPE club_voleibol SYSTEM "./club.dtd"> -->
<!-- @xsd="./club.xsd" -->
<club_voleibol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./club.xsd">
    <tienda ubicacion="Bilbao">
        <articulo marca="Nike" foto="img.jpg" cod="SS123456A">
            <tipoarticulo>Camiseta oficial</tipoarticulo>
            <descripcion>Camiseta oficial del club</descripcion>
            <precio>29.99</precio>
            <comentarios fecha="2023-07-01">Muy cómoda</comentarios>
            <comentarios fecha="2023-07-02">Muy cómoda</comentarios>
        </articulo>
    </tienda>
    <!--  Información del equipo  -->
    <equipo categoria="Segunda">
        <jugadores>
            <jugador camiseta="7" titular="si">
                <nombre>Luis García</nombre>
                <posicion>Atacante</posicion>
                <nacionalidad>Argentina</nacionalidad>
            </jugador>
            <jugador camiseta="99" titular="no">
                <nombre>Ana Silva</nombre>
                <posicion>Libero</posicion>
                <nacionalidad>Brasil</nacionalidad>
            </jugador>
        </jugadores>
        <denominacion>Club VolleyTeam</denominacion>
        <entrenador>
            <nombre>Julio Velasco</nombre>
            <url>www.wikipedia.org/wiki/Julio_Velasco</url>
        </entrenador>
    </equipo>
    <equipo categoria="Segunda">
        <denominacion>Club VolleyTeam B</denominacion>
        <jugadores>
            <jugador camiseta="7" titular="si">
                <nombre>Luis García</nombre>
                <posicion>Atacante</posicion>
                <nacionalidad>Argentina</nacionalidad>
            </jugador>
            <jugador camiseta="3" titular="no">
                <nombre>Ana Silva</nombre>
                <posicion>Libero</posicion>
                <nacionalidad>Brasil</nacionalidad>
            </jugador>
        </jugadores>
        <entrenador>
            <nombre>Julio Velasco</nombre>
            <url>www.wikipedia.org/wiki/Julio_Velasco</url>
        </entrenador>
    </equipo>
    <!--  Información del partido  -->
    <partido>
        <lugar>Estadio Nacional</lugar>
        <fecha>2023-08-01</fecha>
        <teams>
            <team  puntuacion="20">Equipo A</team>
            <team local="no" puntuacion="25">Equipo B</team>
        </teams>
        <arbitro categoria="internacional">
            <nombre>Juan Pérez</nombre>
            <nacionalidad>Argentina</nacionalidad>
        </arbitro>
    </partido>
    <partido>
        <lugar>Estadio Nacional</lugar>
        <fecha>2023-08-01</fecha>
        <teams>
            <team local="si" puntuacion="20">Equipo A</team>
            <team local="no" puntuacion="25">Equipo B</team>
        </teams>
        <arbitro categoria="nacional">
            <nombre>Juan Pérez</nombre>
            <nacionalidad>Argentina</nacionalidad>
        </arbitro>
    </partido>
</club_voleibol>
