=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/genomica/genomica.dtd
<!ELEMENT laboratorio (nombrelabo, fundacion, investigadores)>
<!ELEMENT nombrelabo (#PCDATA)>
<!ELEMENT fundacion EMPTY>
<!ATTLIST fundacion anio CDATA #REQUIRED>
<!ATTLIST fundacion mes CDATA #REQUIRED>
<!ATTLIST fundacion dia CDATA #REQUIRED>
<!ELEMENT investigadores (investigador+)>
<!ELEMENT investigador (nombreInves, especialidad, proyectos+, publicaciones+)>
<!ATTLIST investigador id CDATA #REQUIRED>
<!ELEMENT nombreInves (#PCDATA)>
<!ELEMENT especialidad (#PCDATA)>
<!ELEMENT proyectos (proyecto+)>
<!ELEMENT proyecto (titulo, descripcion, responsable, fechas, secuenciasGenomicas)>
<!ATTLIST proyecto id CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT responsable (#PCDATA)>
<!ELEMENT fechas (inicio, fin)>
<!ELEMENT inicio EMPTY>
<!ATTLIST inicio anio CDATA #REQUIRED>
<!ATTLIST inicio mes CDATA #REQUIRED>
<!ATTLIST inicio dia CDATA #REQUIRED>
<!ELEMENT fin EMPTY>
<!ATTLIST fin anio CDATA #REQUIRED>
<!ATTLIST fin mes CDATA #REQUIRED>
<!ATTLIST fin dia CDATA #REQUIRED>
<!ELEMENT secuenciasGenomicas (secuencia+)>
<!ELEMENT secuencia (nombre, contenido)>
<!ATTLIST secuencia id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT publicaciones (publicacion+)>
<!ELEMENT publicacion (titulopubli, revista, fechaPublicacion)>
<!ELEMENT titulopubli (#PCDATA)>
<!ELEMENT revista (#PCDATA)>
<!ELEMENT fechaPublicacion EMPTY>
<!ATTLIST fechaPublicacion anio CDATA #REQUIRED>
<!ATTLIST fechaPublicacion mes CDATA #REQUIRED>
<!ATTLIST fechaPublicacion dia CDATA #REQUIRED>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/genomica/genomica.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE laboratorio SYSTEM "genomica.dtd">
<laboratorio>
    <nombrelabo>GenoLab Innovations</nombrelabo>
    <fundacion anio="2005" mes="09" dia="25"/>
    <investigadores>
        <investigador id="I001">
            <nombreInves>Dr. Ana García</nombreInves>
            <especialidad>Genómica Comparativa</especialidad>
            <proyectos>
                <proyecto id="P001">
                    <titulo>Estudio de Variabilidad Genómica en Poblaciones Humanas</titulo>
                    <descripcion><![CDATA[
                        Investigación para entender la variabilidad genómica en diferentes poblaciones humanas.
                    ]]></descripcion>
                    <responsable>Dr. Javier Martínez</responsable>
                    <fechas>
                        <inicio anio="2018" mes="04" dia="01"/>
                        <fin anio="2023" mes="12" dia="31"/>
                    </fechas>
                    <secuenciasGenomicas>
                        <secuencia id="S001">
                            <nombre>Secuencia A</nombre>
                            <contenido><![CDATA[
                                ATCGTACGTACGTACGTA
                                GATCGATCGATCGATCG
                                TGCATGCATGCATGCA
                            ]]></contenido>
                        </secuencia>
                    </secuenciasGenomicas>
                </proyecto>
            </proyectos>
            <publicaciones>
                <publicacion>
                    <titulopubli>Avances en Genómica Comparativa</titulopubli>
                    <revista>Journal of Genomics</revista>
                    <fechaPublicacion anio="2021" mes="08" dia="15"/>
                </publicacion>
            </publicaciones>
        </investigador>
    </investigadores>
</laboratorio>
