=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/factura/factura.dtd
<!ELEMENT factura (cliente, productos+, total)>
<!ELEMENT cliente (nombre, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombre, precio, cantidad)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/factura/factura.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">
<factura>
    <cliente>
        <nombre>Juan PÃ©rez</nombre>
        <direccion>Calle Principal, 123</direccion>
    </cliente>
    <productos>
        <producto>
            <nombre>Camiseta</nombre>
            <precio>20.00</precio>
            <cantidad>2</cantidad>
        </producto>
        <producto>
            <nombre>Zapatos</nombre>
            <precio>50.00</precio>
            <cantidad>1</cantidad>
        </producto>
    </productos>
    <total>90.00</total>
</factura>
