=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/xsd/ejercicios/estudiante/estudiante.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="estudiante" type="EstudianteType"/>

  <xs:complexType name="EstudianteType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="edad" type="xs:integer"/>
      <xs:element name="curso" type="xs:string"/>
      <xs:element name="notas" type="NotasType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="NotasType">
    <xs:sequence>
      <xs:element name="nota" type="NotaType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="NotaType">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attribute name="asignatura" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/xsd/ejercicios/estudiante/estudiante.xml
<?xml version="1.0" encoding="UTF-8"?>
<estudiante xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="estudiante.xsd">
    <nombre>Juan Pérez</nombre>
    <edad>20</edad>
    <curso>Informática</curso>
    <notas>
        <nota asignatura="Matemáticas">85</nota>
        <nota asignatura="Programación">92</nota>
        <nota asignatura="Inglés">78</nota>
    </notas>
</estudiante>
