=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/libro/libros.dtd
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (titulo, autor, publicacion)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT publicacion (#PCDATA)>

=== IosuVitoria/FP/Lenguaje de marcas/UD3_XML/Repaso/dtd/ejercicios/libro/libro.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE biblioteca SYSTEM "libros.dtd">
<biblioteca>
    <libro>
        <titulo>Introducción a XML</titulo>
        <autor>Juan Pérez</autor>
        <publicacion>Año 2020</publicacion>
    </libro>
    <libro>
        <titulo>Programación en Java</titulo>
        <autor>Maria López</autor>
        <publicacion>Año 2019</publicacion>
    </libro>
</biblioteca>
